# 端口
server:
  port: 10888
# 指定配置文件所在的git工程路径
spring:
  cloud:
    config:
      server:
        git:
          # 1. 单库：配置文件只搜索url目录下的searchPaths
          # uri: https://github.com/hryou0922/spring_cloud.git
          # searchPaths: cloud-config-git/simple2
          # 2. 多库：
          uri: https://github.com/hryou0922/spring_cloud.git
          searchPaths: cloud-config-git/simple2/default
          repos:
            simple:
              # 匹配 application = simple
              patten: simple
              uri: https://github.com/hryou0922/spring_cloud/tree/master/cloud-config-git/simple2/configsimple
            special:
              # 匹配 application like special* 和 profile like special的记录
              pattern: special*/dev,*special*/dev*
              uri: https://github.com/hryou0922/spring_cloud/tree/master/cloud-config-git/simple2/configspecial
            local:
              # 匹配 application like local*
              pattern: local*
              uri: file:/home/configsvc/config-repo
  application:
    name: config-config-gitsimple2
# 服务器注册服务器的zone
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:10761/eureka/
  instance:
    prefer-ip-address: true
