# 端口
server:
  port: 10888
# 指定配置文件所在的git工程路径
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hryou0922/spring_cloud.git
          searchPaths: cloud-config-git/simple2
  application:
    name: config-config-gitsimple2
# 服务器注册服务器的zone
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:10761/eureka/
  instance:
    prefer-ip-address: true
