

management:
  security:
    # 关闭安全，可以访问这个接口 http://10.240.80.69:14601/routes
    # 查看详细信息： http://10.240.80.69:14601/routes，
    enabled: false

zuul:
  # 此参数设置忽略哪些服务，如果是*，则忽略所有服务
  # ignoredServices: '*'
  # 此参数可以设置忽略以下的请求
  # ignoredPatterns: /**/admin/**
  routes:
    api-url:
      # 通过url直接映射
      # 所有到Zuul的中规则为：/api-a-url/**的访问都映射到http://127.0.0.1:15601/上，
      # 也就是说当我们访问http://127.0.0.1:14602/api-url/zuul-test/simple的时候，Zuul会将该请求路由到：http://127.0.0.1:15601/zuul-test/simple
      path: /api-url/**
      # 对于url映射不是通过HystrixCommand执行，也不能通过ribbon进行负载，需要进行额外配置，详细见spring 文档
      url: http://127.0.0.1:15601/